language: node_js
cache:
  directories:
    - node_modules
node_js:
  - '8'
env:
  - NODE_ENV=production
before_install:
  - npm install -g yarn jest
install: yarn
script: yarn build && yarn test:client
