language: node_js
cache:
  directories:
    - node_modules
node_js:
  - '8'
env:
  - NODE_ENV=production
before_install:
  - "npm install -g yarn"
install: echo Installing && yarn install
script:
  - echo 'running tests...' && echo $(pwd) && yarn test:client
