version: '2'

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=sa.pg.01
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  data:
